@startuml

Class Vehicle {
    - matricula : String
    - mida : MidaVehicle
    + getMatricula()
    + getMida()
}

Class Motocicleta extends Vehicle{
    + Motocicleta (matricula : String)
    

}

Class Cotxe extends Vehicle{
    + Cotxe (matricula : String)

}

Class Camio extends Vehicle{
    + Camio (matricula : String)

}

ENUM TipusPlaces {
    COMPACTES,
    REGULARS,
    GRANS
}

Class Coordenada{
    - x : double
    - y : double
}




Class PlacaAparcament{
    - numero : Int
    - estat
    - vehicleAparcat : Vehicle
    - coordenades : Coordenada[]
}

Class PlacaCompacta extends PlacaAparcament{
    - PlacaCompacta (numero : Int, coordenades : Coordenada[])

}

Class PlacaRegular extends PlacaAparcament{
    - PlacaRegular (numero : Int, coordenades : Coordenada[])

}

Class PlacaGran extends PlacaAparcament{
    - PlacaGran (numero : Int, coordenades : Coordenada[])

}


Vehicle "1" -- "1" PlacaAparcament 

PlacaAparcament "*" --> "*" Coordenada


Class PlacesParking {
    - placesParking : PlacaAparcament[]
    + aparcar() : Vehicle
    + desaparcar() : Ticket
    + MostrarEstat()
    + getTickets() : int
}


@enduml